# GATEWAY PROD - backend server port
server:
  port: ${SERVER_PORT}

# frontend server host
frontend:
  user-host: ${SPRING_FRONTEND_USER_HOST}
  admin-host: ${SPRING_FRONTEND_ADMIN_HOST}

# project
farm2pot:
  core-service:
    url: ${CORE_SERVICE_URL}

# Spring
spring:
  application:
    name: gateway-service
  redis:
    host: farm2pot-redis-master   # Redis 서버 호스트
    port: 6379        # Redis 서버 포트
    password: ""      # Redis에 비밀번호가 있다면 입력
    timeout: 2000ms   # 연결 타임아웃

# SECUTIRY
jwt:
  security:
    key: 6rCA7J6Q6rOgIO2GoOydtO2UhOuhnOygne2KuCBqd3Qgc2VjcmV0IO2CpOyeheuLiOuLpA==
    whiteList:
      - /api/user/auth/**
      - /api/test/**

# Route 설정
routes:
  core:
    url: ${CORE_SERVICE_URL}
    path: /api/core/**
  user:
    url: ${USER_SERVICE_URL}
    path: /api/user/**
  admin:
    url: ${ADMIN_SERVICE_URL}
    path: /api/admin/**
  subscription:
    url: ${SUBSCRIPTION_SERVICE_URL}
    path: /api/subscription/**

logging:
  level:
    com.farm2pot: ${LOGGING_LEVEL_COM_FARM2POT}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
    org.springframework.boot.web.embedded.netty: DEBUG
