# GATEWAY DEV
server:
  port: 19080

# frontend server host
frontend:
  user-host: localhost:14001
  admin-host: localhost:14002

# project
farm2pot:
  core-service:
    url: http://localhost:18080

# Spring
spring:
  application:
    name: gateway-service
  redis:
    host: localhost   # Redis 서버 호스트
    port: 26379        # Redis 서버 포트
    password: ""      # Redis에 비밀번호가 있다면 입력
    timeout: 2000ms   # 연결 타임아웃

# SECUTIRY
jwt:
  security:
    key: 6rCA7J6Q6rOgIO2GoOydtO2UhOuhnOygne2KuCBqd3Qgc2VjcmV0IO2CpOyeheuLiOuLpA==
    whiteList:
      - /api/user/auth/**
      - /api/test/**

# Route 설정
routes:
  core:
    url: http://localhost:18080
    path: /api/core/**
  user:
    url: http://localhost:18081
    path: /api/user/**
  admin:
    url: http://localhost:18082
    path: /api/admin/**
  subscription:
    url: http://localhost:18083
    path: /api/subs/**

logging:
  level:
    com.farm2pot: DEBUG
    org.springframework: WARN
    org.springframework.boot.web.embedded.netty: DEBUG


