# USER DEV - backend server port
server:
  port: 18081

# project
farm2pot:
  core-service:
    url: http://localhost:18080

# Spring
spring:
  datasource:
    url: jdbc:mysql://localhost:23306/farm2pot?allowPublicKeyRetrieval=true&useSSL=false
    username: farm2pot
    password: farm2pot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true  # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅

  redis:
    host: localhost
    port: 26379

# SECUTIRY
jwt:
  security:
    key: 6rCA7J6Q6rOgIO2GoOydtO2UhOuhnOygne2KuCBqd3Qgc2VjcmV0IO2CpOyeheuLiOuLpA==
    expiration: 360000   # 1시간 (단위: 밀리초)
    refresh-expiration: 360000 # 테스트를 위해 360000    1209600000  # 2주 (선택)
    whiteList:
      - /api/user/public/**

kafka:
  bootstrap-servers: localhost:19092



